### ISSUE TITLE
No original dex files error

### ISSUE THREAD

**Issue by wikpunGitHub** [NordicSemiconductor/Android-nRF-Blinky#5]
Hi, I got the below error when I run the app. Would you please help?

Suppressed: java.io.IOException: No original dex files found for dex location (arm64) /data/app/no.nordicsemi.android.nrfblinky-a

**Comment by roshanrajaratnam** [comment]
Hi @wikpunGitHub have you tried clean building the app.. etc?

**Comment by wikpunGitHub** [comment]
Hi Roshan:

Yes, I pressed the "Clean Project" in the "Build" menu inside Android
Studio and it still doesn't work. Here is the complete debug output for
your reference.

*Build Output:*
completed successfully 13s 469ms
Run build 13s 368ms
Load build 5ms
Configure build 84ms
Calculate task graph 302ms
Run tasks 12s 975ms
*Debug Output:*

04/26 13:51:19: Launching app
$ adb install-multiple -r -t
C:\Users\Wik\Downloads\Android-nRF-Blinky\app\build\intermediates\resources\instant-run\debug\resources-debug.apk
C:\Users\Wik\Downloads\Android-nRF-Blinky\app\build\intermediates\split-apk\debug\dep\dependencies.apk
C:\Users\Wik\Downloads\Android-nRF-Blinky\app\build\intermediates\split-apk\debug\slices\slice_3.apk
C:\Users\Wik\Downloads\Android-nRF-Blinky\app\build\intermediates\split-apk\debug\slices\slice_2.apk
C:\Users\Wik\Downloads\Android-nRF-Blinky\app\build\intermediates\split-apk\debug\slices\slice_4.apk
C:\Users\Wik\Downloads\Android-nRF-Blinky\app\build\intermediates\split-apk\debug\slices\slice_0.apk
C:\Users\Wik\Downloads\Android-nRF-Blinky\app\build\intermediates\split-apk\debug\slices\slice_5.apk
C:\Users\Wik\Downloads\Android-nRF-Blinky\app\build\intermediates\split-apk\debug\slices\slice_1.apk
C:\Users\Wik\Downloads\Android-nRF-Blinky\app\build\intermediates\split-apk\debug\slices\slice_6.apk
C:\Users\Wik\Downloads\Android-nRF-Blinky\app\build\intermediates\split-apk\debug\slices\slice_7.apk
C:\Users\Wik\Downloads\Android-nRF-Blinky\app\build\intermediates\split-apk\debug\slices\slice_9.apk
C:\Users\Wik\Downloads\Android-nRF-Blinky\app\build\intermediates\split-apk\debug\slices\slice_8.apk
C:\Users\Wik\Downloads\Android-nRF-Blinky\app\build\intermediates\instant-run-apk\debug\app-debug.apk
Split APKs installed
$ adb shell am start -n
"no.nordicsemi.android.nrfblinky/no.nordicsemi.android.blinky.SplashScreenActivity"
-a android.intent.action.MAIN -c android.intent.category.LAUNCHER -D
Waiting for application to come online: no.nordicsemi.android.nrfblinky |
no.nordicsemi.android.nrfblinky.test
Waiting for application to come online: no.nordicsemi.android.nrfblinky |
no.nordicsemi.android.nrfblinky.test
Connecting to no.nordicsemi.android.nrfblinky
Connected to the target VM, address: 'localhost:8600', transport: 'socket'
Capturing and displaying logcat messages from application. This behavior
can be disabled in the "Logcat output" section of the "Debugger" settings
page.
E/Zygote: isWhitelistProcess - Process is Whitelisted
E/libpersona: scanKnoxPersonas
              Couldn't open the File - /data/system/users/0/personalist.xml
- No such file or directory
W/SELinux: SELinux selinux_android_compute_policy_index : Policy Index[2],
Con:u:r:zygote:s0 RAM:SEPF_SM-G9650_8.0.0_0002, [-1 -1 -1 -1 0 1]
I/SELinux: SELinux: seapp_context_lookup: seinfo=untrusted,
level=s0:c512,c768, pkgname=no.nordicsemi.android.nrfblinky
I/zygote64: Late-enabling -Xcheck:jni
D/TimaKeyStoreProvider: TimaKeyStore is not enabled: cannot add
TimaSignature Service and generateKeyPair Service
D/ActivityThread: Added TimaKeyStore provider
W/ActivityThread: Application no.nordicsemi.android.nrfblinky is waiting
for the debugger on port 8100...
I/System.out: Sending WAIT chunk
I/zygote64: Debugger is active
I/System.out: Debugger has connected
              waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: debugger has settled (1305)
I/InstantRun: starting instant run server: is main process
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: no.nordicsemi.android.nrfblinky, PID: 30527
                  java.lang.RuntimeException: Unable to get provider
android.arch.lifecycle.ProcessLifecycleOwnerInitializer:
java.lang.ClassNotFoundException: Didn't find class
"android.arch.lifecycle.ProcessLifecycleOwnerInitializer" on path:
DexPathList[[zip file
"/data/app/no.nordicsemi.android.nrfblinky-CsfVyNzDLkH7aqzfLGDFzw==/base.apk",
zip file
"/data/app/no.nordicsemi.android.nrfblinky-CsfVyNzDLkH7aqzfLGDFzw==/split_lib_dependencies_apk.apk",
zip file
"/data/app/no.nordicsemi.android.nrfblinky-CsfVyNzDLkH7aqzfLGDFzw==/split_lib_resources_apk.apk",
zip file
"/data/app/no.nordicsemi.android.nrfblinky-CsfVyNzDLkH7aqzfLGDFzw==/split_lib_slice_0_apk.apk",
zip file
"/data/app/no.nordicsemi.android.nrfblinky-CsfVyNzDLkH7aqzfLGDFzw==/split_lib_slice_1_apk.apk",
zip file
"/data/app/no.nordicsemi.android.nrfblinky-CsfVyNzDLkH7aqzfLGDFzw==/split_lib_slice_2_apk.apk",
zip file
"/data/app/no.nordicsemi.android.nrfblinky-CsfVyNzDLkH7aqzfLGDFzw==/split_lib_slice_3_apk.apk",
zip file
"/data/app/no.nordicsemi.android.nrfblinky-CsfVyNzDLkH7aqzfLGDFzw==/split_lib_slice_4_apk.apk",
zip file
"/data/app/no.nordicsemi.android.nrfblinky-CsfVyNzDLkH7aqzfLGDFzw==/split_lib_slice_5_apk.apk",
zip file
"/data/app/no.nordicsemi.android.nrfblinky-CsfVyNzDLkH7aqzfLGDFzw==/split_lib_slice_6_apk.apk",
zip file
"/data/app/no.nordicsemi.android.nrfblinky-CsfVyNzDLkH7aqzfLGDFzw==/split_lib_slice_7_apk.apk",
zip file
"/data/app/no.nordicsemi.android.nrfblinky-CsfVyNzDLkH7aqzfLGDFzw==/split_lib_slice_8_apk.apk",
zip file
"/data/app/no.nordicsemi.android.nrfblinky-CsfVyNzDLkH7aqzfLGDFzw==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/no.nordicsemi.android.nrfblinky-CsfVyNzDLkH7aqzfLGDFzw==/lib/arm64,
/system/lib64, /vendor/lib64]]
                      at
android.app.ActivityThread.installProvider(ActivityThread.java:6575)
                      at
android.app.ActivityThread.installContentProviders(ActivityThread.java:6127)
                      at
android.app.ActivityThread.handleBindApplication(ActivityThread.java:6037)
                      at android.app.ActivityThread.-wrap1(Unknown Source:0)
                      at
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
                      at
android.os.Handler.dispatchMessage(Handler.java:105)
                      at android.os.Looper.loop(Looper.java:164)
                      at
android.app.ActivityThread.main(ActivityThread.java:6938)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at
com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
                      at
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
E/AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find
class "android.arch.lifecycle.ProcessLifecycleOwnerInitializer" on path:
DexPathList[[zip file
"/data/app/no.nordicsemi.android.nrfblinky-CsfVyNzDLkH7aqzfLGDFzw==/base.apk",
zip file
"/data/app/no.nordicsemi.android.nrfblinky-CsfVyNzDLkH7aqzfLGDFzw==/split_lib_dependencies_apk.apk",
zip file
"/data/app/no.nordicsemi.android.nrfblinky-CsfVyNzDLkH7aqzfLGDFzw==/split_lib_resources_apk.apk",
zip file
"/data/app/no.nordicsemi.android.nrfblinky-CsfVyNzDLkH7aqzfLGDFzw==/split_lib_slice_0_apk.apk",
zip file
"/data/app/no.nordicsemi.android.nrfblinky-CsfVyNzDLkH7aqzfLGDFzw==/split_lib_slice_1_apk.apk",
zip file
"/data/app/no.nordicsemi.android.nrfblinky-CsfVyNzDLkH7aqzfLGDFzw==/split_lib_slice_2_apk.apk",
zip file
"/data/app/no.nordicsemi.android.nrfblinky-CsfVyNzDLkH7aqzfLGDFzw==/split_lib_slice_3_apk.apk",
zip file
"/data/app/no.nordicsemi.android.nrfblinky-CsfVyNzDLkH7aqzfLGDFzw==/split_lib_slice_4_apk.apk",
zip file
"/data/app/no.nordicsemi.android.nrfblinky-CsfVyNzDLkH7aqzfLGDFzw==/split_lib_slice_5_apk.apk",
zip file
"/data/app/no.nordicsemi.android.nrfblinky-CsfVyNzDLkH7aqzfLGDFzw==/split_lib_slice_6_apk.apk",
zip file
"/data/app/no.nordicsemi.android.nrfblinky-CsfVyNzDLkH7aqzfLGDFzw==/split_lib_slice_7_apk.apk",
zip file
"/data/app/no.nordicsemi.android.nrfblinky-CsfVyNzDLkH7aqzfLGDFzw==/split_lib_slice_8_apk.apk",
zip file
"/data/app/no.nordicsemi.android.nrfblinky-CsfVyNzDLkH7aqzfLGDFzw==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/no.nordicsemi.android.nrfblinky-CsfVyNzDLkH7aqzfLGDFzw==/lib/arm64,
/system/lib64, /vendor/lib64]]
                      at
dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
                      at
java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                      at
java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                      at
android.app.ActivityThread.installProvider(ActivityThread.java:6560)
                      ... 10 more
                  Suppressed: java.io.IOException: No original dex files
found for dex location (arm64)
/data/app/no.nordicsemi.android.nrfblinky-CsfVyNzDLkH7aqzfLGDFzw==/split_lib_resources_apk.apk
                      at dalvik.system.DexFile.openDexFileNative(Native
Method)
                      at dalvik.system.DexFile.openDexFile(DexFile.java:353)
                      at dalvik.system.DexFile.<init>(DexFile.java:100)
                      at dalvik.system.DexFile.<init>(DexFile.java:74)
                      at
dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
                      at
dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
                      at
dalvik.system.DexPathList.<init>(DexPathList.java:157)
                      at
dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
                      at
dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
                      at
com.android.internal.os.PathClassLoaderFactory.createClassLoader(PathClassLoaderFactory.java:43)
                      at
android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:69)
                      at
android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:36)
                      at
android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:676)
                      at
android.app.LoadedApk.getClassLoader(LoadedApk.java:709)
                      at
android.app.LoadedApk.getResources(LoadedApk.java:942)
                      at
android.app.ContextImpl.createAppContext(ContextImpl.java:2303)
                      at
android.app.ActivityThread.handleBindApplication(ActivityThread.java:5937)
                      ... 8 more


Best Regards,

Wik

2018-04-26 13:43 GMT+08:00 Roshan Rajaratnam <notifications@github.com>:

**Comment by wikpunGitHub** [comment]
Hi Roshan:

I also cleaned it in Gradle pane and it still shows the same error. Please
see the below picture for reference. Thanks!

Best Regards,

Wik




2018-04-26 13:52 GMT+08:00 Wik Pun <wikpun@gmail.com>:

**Comment by clicit** [comment]
@wikpunGitHub Try to disable Instant Run!

**Comment by pardis-sargarmi** [comment]
kk
